import type { Metadata } from "next";
import { Nunito, Bricolage_Grotesque } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
// local components
import Header from "@/components/layout/header";
import Footer from "@/components/layout/footer";

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
});

const bricolageGrotesque = Bricolage_Grotesque({
  variable: "--font-bricolage-grotesque",
  subsets: ["latin"],
});

const bricolageGrotesqueCondensed = localFont({
  variable: "--font-bricolage-grotesque-condensed",
  src: [
    {
      path: "../public/fonts/webfonts/bricolage-grotesque-condensed/BricolageGrotesque48ptCondensed-ExtraLight.woff2",
      weight: "200",
      style: "normal",
    },
    {
      path: "../public/fonts/webfonts/bricolage-grotesque-condensed/BricolageGrotesque48ptCondensed-Light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "../public/fonts/webfonts/bricolage-grotesque-condensed/BricolageGrotesque48ptCondensed-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/webfonts/bricolage-grotesque-condensed/BricolageGrotesque48ptCondensed-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/fonts/webfonts/bricolage-grotesque-condensed/BricolageGrotesque48ptCondensed-SemiBold.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "../public/fonts/webfonts/bricolage-grotesque-condensed/BricolageGrotesque48ptCondensed-Bold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "../public/fonts/webfonts/bricolage-grotesque-condensed/BricolageGrotesque48ptCondensed-ExtraBold.woff2",
      weight: "800",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "Tasty Fruit",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${nunito.variable} ${bricolageGrotesque.variable} ${bricolageGrotesqueCondensed.variable} antialiased flex flex-col`}
      >
        {/* Header - Fixed positioning handled internally */}
        <Header />

        {/* Main Content Area */}
        <main className="flex-1 w-full min-h-screen">
          <div className="w-full h-auto mx-auto px-4 sm:px-6 lg:px-22 font-nunito py-12 lg:py-20">
            {children}
          </div>
        </main>

        {/* Footer - Sticky to bottom */}
        <Footer />
      </body>
    </html>
  );
}
